# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/configuration/all/
# -------------------------------------------------------------------------------------

# website title
title = "FixIt"
# hostname (and path) to the root
baseURL = "http://localhost:1313"
# theme list
# theme = ["FixIt"] # enable in your site config file
# determines default content language ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "en"
# language code ["en", "zh-CN", "fr", "pl", ...]
locale = "en"
# language name ["English", "简体中文", "Français", "Polski", ...]
label = "English"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = false
# timezone local
timeZone = "Asia/Shanghai"
# copyright description used only for seo schema
copyright = ""
# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true
# the capitalization rules to follow, optional values: ["ap", "chicago", "go", "firstupper", "none"]
titleCaseStyle = "ap"
# whether to capitalize automatic list titles
capitalizeListTitles = false
# the main sections of a site
# if set, the MainSections method on the Site object returns the given sections,
# otherwise it returns the section with the most pages.
mainSections = [
  "contributing",
  "documentation",
  "ecosystem",
  "guides",
  "references",
  "guides",
]
# the editor to use when creating new content
newContentEditor = "code"
# ignore some build warnings and errors
ignoreLogs = [
  "error-get-remote-json",
  "error-get-gh-repo",
  "error-remote-getjson",
  "error-missing-instagram-accesstoken",
  "err-youtube-remote",
  "warning-dev-version",
  "shortcode-x-getremote",
  "warning-remote-image",
]
