# -------------------------------------------------------------------------------------
# Markup Configuration
# See: https://gohugo.io/configuration/markup/
# -------------------------------------------------------------------------------------

_merge = "shallow"
