# -------------------------------------------------------------------------------------
# Modules Configuration | 模块配置
# See: https://gohugo.io/configuration/module/
# -------------------------------------------------------------------------------------

[[imports]]
path = "github.com/hugo-fixit/FixIt"
# 本地调试时不要指定 version
version = "main"

[[imports]]
path = "github.com/hugo-fixit/cmpt-santa-hat"
version = "latest"

[[imports]]
path = "github.com/hugo-fixit/cmpt-translate"
version = "latest"

[[imports]]
path = "github.com/hugo-fixit/component-projects"
version = "latest"

[[imports]]
path = "github.com/hugo-fixit/shortcode-asciinema"
version = "latest"

[[imports]]
path = "github.com/hugo-fixit/shortcode-caniuse"
version = "latest"

[[imports]]
path = "github.com/hugo-fixit/shortcode-docs-bookmark"
version = "latest"

[[imports]]
path = "github.com/hugo-fixit/shortcode-missing-translation"
version = "latest"

[[imports]]
path = "github.com/hugo-fixit/shortcode-rewards"
version = "latest"

[hugoVersion]
extended = true
min = "0.156.0"
