# -------------------------------------------------------------------------------------
# Permalinks Configuration
# See: https://gohugo.io/configuration/permalinks/
# -------------------------------------------------------------------------------------

[page]
documentation = "/docs/:sections[1:]/:slugorcontentbasename"

[section]
documentation = "/docs/:sections[1:]"

# [taxonomy]
# [term]
