# -------------------------------------------------------------------------------------
# Sitemap Configuration
# See: https://gohugo.io/configuration/sitemap/
# -------------------------------------------------------------------------------------

changefreq = "weekly"
disable = false
filename = "sitemap.xml"
priority = 0.5
