minimumReleaseAgeExclude:
  - markdownlint-cli2@0.23.1
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # 30 days in minutes
allowBuilds:
  core-js: false
  simple-git-hooks: true
