# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#theme-configuration
# -------------------------------------------------------------------------------------

[post_chat]
enable = false
hot_words = false

[post_summary]
enable = false

# Developer options
# Configure with environment variable HUGO_PARAMS_GHTOKEN=xxx, see https://gohugo.io/functions/os/getenv/#examples
[dev]
enable = false
c4u = true

# -------------------------------------------------------------------------------------
# Theme Components Configuration
# -------------------------------------------------------------------------------------

# Content adapters config for component projects
# https://github.com/hugo-fixit/component-projects
# [TODO] migrate to snake_case
[projectsAdapters]
enable = false
