# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/docs/getting-started/configuration/params/
# -------------------------------------------------------------------------------------

[comment]
enable = true

[comment.giscus]
enable = true
repo = "hugo-fixit/FixIt"
repo_id = "R_kgDOGihPtQ"
category = "General"
category_id = "DIC_kwDOGihPtc4CApHX"
mapping = "title"
strict = "0"
term = ""
reactions_enabled = "1"
emit_metadata = "0"
input_position = "top" # ["top", "bottom"]
light_theme = "light"
dark_theme = "dark_dimmed"
lazy_load = true

[busuanzi]
enable = true
source = "https://vercount.one/js"
site_views = true
page_views = true
